---
apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: test
spec:
  type: NodePort
  ports:
    - port: 10080
      name: test
      targetPort: 8080
  selector:
    app: test
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test
spec:
  serviceName: "test"
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      imagePullSecrets:
        - name: $SECRET_NAME
      containers:
        - name: test
          image: $IMAGE_NAME
          ports:
            - containerPort: 8080
  podManagementPolicy: "Parallel"